name: bread_bank
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  carousel_slider: ^5.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  sqflite_common_ffi: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/grocery_icon.png
    - assets/car_icon.png
    - assets/restaurant_icon.png
    - assets/home_icon.png
    - assets/expense_icon.png
    - assets/paid_icon.png
    - assets/utilities_icon.png
    - assets/vacation_icon.png
    - assets/default_icon.png
    - assets/goals_icon.png
    - assets/insights_icon.png
    - assets/entertainment_icon.png
    - assets/other_icon.png
    
    



